SELECT f."JUDUL",
       MIN(TRUNC(MONTHS_BETWEEN(SYSDATE, m."TGL_LAHIR")/12)) AS UMUR_TERENDAH
FROM "FILM" f
JOIN "JADWAL" j ON f."ID_FILM" = j."ID_FILM"
JOIN "TRANSAKSI" t ON j."ID_JADWAL" = t."ID_JADWAL"
JOIN "MEMBER" m ON t."ID_MEMBER" = m."ID_MEMBER"
WHERE f."DURASI" = (
    SELECT MIN("DURASI")
    FROM "FILM"
)
GROUP BY f."JUDUL";


SELECT th."ID_THEATER", th."KELAS", COUNT(*) AS TOTAL_PAKAI
FROM "THEATER" th
JOIN "JADWAL" j ON th."ID_THEATER" = j."ID_THEATER"
JOIN "TRANSAKSI" t ON j."ID_JADWAL" = t."ID_JADWAL"
GROUP BY th."ID_THEATER", th."KELAS"
HAVING COUNT(*) = (
    SELECT MAX(jumlah)
    FROM (
        SELECT COUNT(*) AS jumlah
        FROM "JADWAL" j2
        JOIN "TRANSAKSI" t2 ON j2."ID_JADWAL" = t2."ID_JADWAL"
        GROUP BY j2."ID_THEATER"
    )
);