SELECT j.ID_THEATER, f.JUDUL, SUM(t2.HARGA) AS TOTAL_PENDAPATAN
FROM TRANSAKSI t
JOIN JADWAL j ON t.ID_JADWAL = j.ID_JADWAL
JOIN FILM f ON j.ID_FILM = f.ID_FILM
JOIN THEATER t2 ON j.ID_THEATER = t2.ID_THEATER
GROUP BY j.ID_THEATER, f.JUDUL
HAVING SUM(t2.HARGA) > 150000;

SELECT f.JUDUL, COUNT(*) AS JUMLAH_TONTON
FROM TRANSAKSI t
JOIN JADWAL j ON t.ID_JADWAL = j.ID_JADWAL
JOIN FILM f ON j.ID_FILM = f.ID_FILM
WHERE t.STATUS = 'pesan'
GROUP BY f.JUDUL
HAVING COUNT(*) = (
    SELECT MAX(jumlah)
    FROM (
        SELECT COUNT(*) AS jumlah
        FROM TRANSAKSI t2
        JOIN JADWAL j2 ON t2.ID_JADWAL = j2.ID_JADWAL
        WHERE t2.STATUS = 'pesan'
        GROUP BY j2.ID_FILM
    )
);

SELECT j.ID_THEATER, AVG(t2.HARGA) AS RATA_PENDAPATAN
FROM TRANSAKSI t
JOIN JADWAL j ON t.ID_JADWAL = j.ID_JADWAL
JOIN THEATER t2 ON j.ID_THEATER = t2.ID_THEATER
GROUP BY j.ID_THEATER;

SELECT f.JUDUL, j.ID_THEATER, COUNT(*) AS JUMLAH_PUTAR
FROM JADWAL j
JOIN FILM f ON j.ID_FILM = f.ID_FILM
WHERE f.JUDUL = 'Habibie Ainun 3'
GROUP BY f.JUDUL, j.ID_THEATER;